### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by wltjr** [okratitan/Ephoto#2]
Any updates on a new release? It was mentioned a new one would be coming before end of year, 2017 in issue https://github.com/okratitan/Ephoto/issues/1#issuecomment-349467326.

I can make a snapshot release if needed, but rather an actual release. It does not seem anything has changed in the last year. At times I still experience a crash like in issue #1, but the file is no longer deleted, and it does save the modified image despite the crash. Not sure if that is new, already fixed, etc. Thus curious about a release. Thanks!

**Comment by okratitan** [comment]
I don't foresee this happening unless EFL/Enlightenment can get things together as far as a community and direction goes.

**Comment by wltjr** [comment]
@okratitan that is unfortunate news, but not surprising. I am continuing to move forward what I can  despite the issues. That includes inability to post anything on phab and mailing list posts to edevelop are also filtered/delayed. I am used to it, and just working around those obstacles.
